name = "proofnet"
version = "0.1.0"
defaultTargets = ["Proofnet"]

[[lean_lib]]
name = "Proofnet"

[[require]]
name = "mathlib"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.27.0"
